FLAGS =  -std=c++20 -o
EXE = out.exe



all: 
	    @echo("task1 or task2")

task1:
		g++ $(FLAGS) $(EXE) $(DEF) matrix.cpp

task2:
		g++ $(FLAGS) $(EXE) $(DEF) server.cpp
		g++ $(FLAGS) test.exe $(DEF) test.cpp