FLAGS =  -fopenmp -o
EXE = out.exe



all: 
	    @echo("task1 or task2 or task3")

task1:
		g++ $(FLAGS) $(EXE) $(DEF) DGEMV.cpp 

task2:
		g++ $(FLAGS) $(EXE) $(DEF) integral.cpp 

task3:
		g++ $(FLAGS) $(EXE) $(DEF) iterdgemv.cpp 

